version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: es-course
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      
    ports:
      - "9200:9200"
